### PR TITLE
Updated all npm dependencies

### PR DESCRIPTION
**Pull request by JuanMaRuiz**
[Previous PR](https://github.com/vsiakka/gherkin-lint/pull/119)

Best regards.

### CODE REVIEW

**Comment by michelle-lim** [comment]
I would love it if this update could get merged asap! (: 
When running `npm audit` on my project, it looks like the lodash dependency in this repository has a security vulnerability. 
https://www.npmjs.com/advisories/577

**Comment by vsiakka** [comment]
Thank you @JuanMaRuiz !

**Comment by vsiakka** [comment]
published with v3.0.0 (major version bump since we're dropping support for node 4, 5 and iojs).

**Comment by JuanMaRuiz** [comment]
Many thanks @vsiakka 😃

**Pull request merged**
