### PR TITLE
Fixed on/off rule check

### PR DESCRIPTION
**Pull request by gd46**
Fixes this defect: 

https://github.com/vsiakka/gherkin-lint/issues/73

### CODE REVIEW

**Comment by vsiakka** [comment]
Thanks for the fix!

**Comment by gd46** [comment]
Hi @vsiakka is it possible to bump the package version in npm? Thanks!

**Comment by vsiakka** [comment]
Ooops, it's up in the public npm registry now :)

**Comment by gd46** [comment]
Great thanks!

**Pull request merged**
