### PR TITLE
New rule for issues #97, #100 and #101

### PR DESCRIPTION
**Pull request by josemenveg**
Created the rules for issues:
- #97 
- #100 
- #101 

There is a small change in _no-restricted-tags_ rule.

There was an issues with the error message, it showed the scenario/background line instead of the tag line.
@znevrly and @ajthesnare ; please, check if it's waht you expected

### CODE REVIEW

**Comment by ajthesnare** [comment]
@josemenveg thanks for tackling these.

I did some checking and `allowed-tags` looks good.  

However, the other 2 throw this error when you add them and try to run `npm run demo`:
```
TypeError: Cannot read property 'forEach' of undefined
```

The problem is that there are 2 features that are empty:
```
a.feature
EmptyFeature.feature
```
Now, these feature are obviously invalid and the rule `no-empty-file` checks for them.  The question is, do you want your functions to blow up because of this or do you want to short circuit them to bail in this case:
```
  if (typeof feature.children === 'undefined') {
    return;
  }
```

**Comment by josemenveg** [comment]
I'm not able to reproduce it.

Anyway, as you can see, I have made and update based in your advise:
```
if (feature.children) {
...
}
```

**Comment by ajthesnare** [comment]
sweet, works without error for me now. 👍

**Comment by vsiakka** [comment]
Sorry for the delay. Released with v2.12.0.

**Pull request merged**
