### PR TITLE
Adds a disallowed steps rule.

### LINKED ISSUE #98: Feature Request: Restricted verbiage in Feature/Scenario/Step names
I'm not sure if others will want a rule like this, but it would be nice to restrict verbiage in naming conventions.  My team has a nasty habit of using terms such as "verify" or "validate" in Feature/Scenario/Step names and it drives me crazy.

### PR DESCRIPTION
**Pull request by jhedstrom**
- This allows either exact matching, or partial patterns to disallow certain steps

### CODE REVIEW

**Comment by xgbuils** [comment]
Hi @jhedstrom! I like it.

However "steps" are well defined in gherkin language and backgrounds and scenarios are not steps. Then `disallow-steps` name is a bit confusing.

Cheers!

**Comment by jhedstrom** [comment]
@xgbuils but this is only checking the text of actual steps, not the text of `Scenarios` or `Background` (or `Feature` for that matter), so I'm not quite following...

**Comment by ajthesnare** [comment]
@jhedstrom thanks for doing this.

However, I would not say this "fixes #98" like your comment says. That feature request also addresses Feature and Scenario names.

Could we add additional rules here:
- disallowed-features
- disallowed-scenarios
- disallowed-backgrounds

I'm fine if they were different pull requests but feel #98 should remain open until all are addressed.

Thoughts?

**Comment by vsiakka** [comment]
@jhedstrom, @ajthesnare, @xgbuils what do you guys think about expanding this rule to be more like AJ suggested here? https://github.com/vsiakka/gherkin-lint/issues/98#issuecomment-417358656
That way we don't have to write almost the same rule 3 times and the configuration will be done with one block. Maybe call it `no-restricted-patterns`? eslint has `no-restricted-imports`

I don't mind making the changes on top of @jhedstrom 's PR for ther, but I want to get alignment before merging the rule so that I don't have to rename it and break backwards compatibility in the future.

**Comment by jhedstrom** [comment]
It was just out of habit that I mentioned this "fixes" #98. I agree the additional checks should be available in follow-up issues. I edited the PR description accordingly.

I'll try and find some time this week to make the changes suggested above regarding the regex variables. Great catch on the performance implications!

**Comment by jhedstrom** [comment]
I think I've addressed the feedback above.

**Comment by jhedstrom** [comment]
Not sure how to remove the 'changes requested' flag, but I think it's been done at this point @vsiakka

**Comment by jhedstrom** [comment]
I completely missed the suggestion in https://github.com/vsiakka/gherkin-lint/pull/126#issuecomment-417992372 to expand this and call it `no-restricted-patterns`. That makes sense to me. I may have some time to work on this again soon.

**Comment by jhedstrom** [comment]
I didn't realize travis had failed. I updated my local npm install and got the same linting failure, so have fixed that now. This should go green :)

**Comment by vsiakka** [comment]
Published with v3.3.0

**Comment by vsiakka** [comment]
Published with v3.3.0

**Pull request merged**
