### PR TITLE
Add required-tags rule

### PR DESCRIPTION
**Pull request by zooduck**

### CODE REVIEW

**Comment by zooduck** [comment]
Build 359.1 is always failing, but I am pretty sure it has nothing to do with my PR. I raised another "empty" PR to test Travis build, and it fails just the same. It would appear that the "indentation" rule tests have an issue with the version of Node you are using for Build 359.1.

**Comment by cujarrett** [comment]
@zooduck - I had to update the CI rules to use Node 10. See #145

**Comment by josemenveg** [comment]
It's an already known issue, you can see it in #146 , #141  and #138 .
I had the same issue in one pull ( #137 ) and I modified the rule to fix it.
It seems that the tags list missed the order in a node version.

**Comment by Nikikuzi** [comment]
@zooduck can you please fix tests errors? @vsiakka can you please help to fix this issue? This bug is pain in our ass a long time

**Comment by zooduck** [comment]
I cannot fix the tests errors. They are related to Node 11. This is defined in the travis.yml. The travis.yml file should not be using Node, it should be specifically using stable Node versions.

This PR is NOT breaking the tests. It is the travis.yml, which needs to be updated by the owner of this repo.

**Comment by zooduck** [comment]
@cujarrett it is not the responsibility of your PR to update core functionality of the repo. That would be a separate PR, and it you did create such a PR, and it was merged, then it should stay merged and not be reverted.

**Comment by zooduck** [comment]
@vsiakka please update your travis.yml - my code is not causing this PR to fail, it is related to some tests that already exist that will not work with Node 11! (In other words, the code that is currently on master would fail your current travis build process - so please fix the travis yml! It is a simple 1 line fix.

**Comment by vsiakka** [comment]
@zooduck  i have fixed the compatibility with node 11 in master, can you rebase?

**Comment by zooduck** [comment]
@vsiakka rebase completed

**Comment by vsiakka** [comment]
@zooduck published with v3.1.0

**Pull request merged**
